version: "3.9"

services:
  db:
    image: postgres:14
    container_name: covid_pg
    restart: always
    environment:
      POSTGRES_USER: covid_user
      POSTGRES_PASSWORD: covid_pass
      POSTGRES_DB: covid_data
    ports:
      - "5432:5432"
    volumes:
      - covid_db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  airflow:
    build:
      context: ./airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://covid_user:covid_pass@db:5432/covid_data
      - AIRFLOW__CORE__FERNET_KEY=python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    depends_on:
      - db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8081:8080"
    command: bash -c "airflow db migrate && airflow users create \
      --username admin --password admin --firstname First --lastname Last \
      --role Admin --email admin@example.com && airflow webserver"

volumes:
  covid_db_data:
